apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: mykafka-cluster
  namespace: kafka
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 4.0.0
    storage:
      type: ephemeral
    config:
      auto.create.topics.enable: false
      default.replication.factor: 2
      delete.topic.enable: true
      min.insync.replicas: 2
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    listeners:
      - name: internal
        port: 9092
        type: internal
        tls: false
  entityOperator:
    topicOperator: {}