apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: mykafka
  namespace: kafka
spec:
  kafka:
    version: 3.7.0
    metadataMode: kraft
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    storage:
      type: ephemeral
  kafkaNodePools:
    - brokerRoles:
        - controller
        - broker
      replicas: 3
      storage:
        type: ephemeral
      roles:
        - controller
        - broker
      template:
        pod:
          metadata:
            labels:
              app: kafka-broker
      resources:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 500m
      id: "pool1"