apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: mykafka-cluster
  namespace: kafka
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 4.0.0
    config:
      auto.create.topics.enable: false
      default.replication.factor: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      min.insync.replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
  kafkaNodePools:
    - metadata:
        name: kafka-pool
      spec:
        replicas: 1
        roles:
          - broker
          - controller
        storage:
          type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}